### ISSUE TITLE
Using Ports instead of per container IP

### ISSUE THREAD

**Issue by distributorofpain** [projectcalico/calico-mesos#69]
Just a question, please dont shoot.  :smile_cat: 

I have a situation where we have SSL certificates being generated via each host and then trusted by all hosts.  Traefik requires this trust to work in order to send SSL traffic on the back end for an end to end SSL setup.

Would it be possible to setup calico to use ports instead of IP per container?  If not, we would have to include the CA cert in the container and generate the cert per container on start up which of course would require additional components loaded into the docker image, thus making it larger.

**Comment by fasaxc** [comment]
Sorry, IP-per-container's pretty fundamental to Calico networking.  We do IP routing on each host to get the packets into the right container and IP routing requires different endpoints to have different IPs.

That said, our distributed firewall piece could be adapted to work with ports but it might be a lot of work.

Just to make sure I understand, you want all the workloads to share an IP so that they can share a certificate, rather than generating a certificate per workload?

**Comment by distributorofpain** [comment]
Correct.  Including openssl and trying to register a cert on bootup per container would provide some additional challenges.  This is assuming we could even determine the hostname during that creation process.

I will let them know.  They were interested in using calico to add security.

Thanks for confirming!
